[toolchain]
channel = "1.80"
components = [
    # For support/crown
    "llvm-tools",
    # For support/crown
    "rustc-dev",
    # For docs building
    "rust-docs",
    # For formatting
    "rustfmt",
]
profile = "minimal"
